//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "asset_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub user_id: String,
    pub symbol: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub before_balance: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub amount: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub after_balance: Option<f64>,
    pub trans_id: String,
    pub change_type: Option<String>,
    pub info: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
