//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "asset_freezes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub user_id: String,
    pub symbol: String,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub freeze_amount: Decimal,
    pub status: Option<i16>,
    #[sea_orm(unique)]
    pub trans_id: String,
    pub freeze_type: Option<String>,
    pub info: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
