//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "assets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub symbol: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_balance: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub freeze_balance: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub avail_balance: Option<f64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
