//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub symbol: String,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))", nullable)]
    pub total_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))", nullable)]
    pub freeze_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))", nullable)]
    pub avail_balance: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
