//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use std::time::SystemTime;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kline")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub base: String,
    pub symbol: String,
    pub period: String,
    pub open_at: SystemTime,
    pub close_at: SystemTime,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub open: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub high: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub low: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub close: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub volume: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
