//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4


pub mod asset_freezes;
pub mod asset_logs;
pub mod assets;
pub mod assets_freezes;
pub mod assets_logs;
pub mod kline;
pub mod order;
pub mod order_auto_no;
pub mod trade_log;
pub mod trade_varieties;
pub mod varieties;
pub mod base;
