//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub base: String,
    pub symbol: String,
    #[sea_orm(unique)]
    pub order_id: String,
    pub order_side: String,
    pub order_type: String,
    pub user_id: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_type = "Double")]
    pub fee_rate: f64,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    #[sea_orm(column_type = "Double")]
    pub freeze_qty: f64,
    #[sea_orm(column_type = "Double")]
    pub freeze_amount: f64,
    #[sea_orm(column_type = "Double")]
    pub avg_price: f64,
    #[sea_orm(column_type = "Double")]
    pub finished_qty: f64,
    #[sea_orm(column_type = "Double")]
    pub finished_amount: f64,
    #[sea_orm(column_type = "Double")]
    pub fee: f64,
    pub status: i16,
    pub nano_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
