//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub base: String,
    pub symbol: String,
    #[sea_orm(unique)]
    pub order_id: String,
    pub order_side: String,
    pub order_type: String,
    pub user_id: String,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub quantity: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub fee_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub freeze_qty: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub freeze_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub avg_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub finished_qty: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub finished_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((40, 20)))")]
    pub fee: Decimal,
    pub status: i16,
    pub nano_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
