//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: String,
    pub base: String,
    pub symbol: String,
    pub trade_id: String,
    pub ask: String,
    pub bid: String,
    pub trade_by: i16,
    pub ask_uid: String,
    pub bid_uid: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    #[sea_orm(column_type = "Double")]
    pub ask_fee_rate: f64,
    #[sea_orm(column_type = "Double")]
    pub ask_fee: f64,
    #[sea_orm(column_type = "Double")]
    pub bid_fee_rate: f64,
    #[sea_orm(column_type = "Double")]
    pub bid_fee: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
