//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_varieties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub symbol: String,
    pub name: String,
    pub target_id: Option<i32>,
    pub base_id: Option<i32>,
    pub price_decimals: Option<i64>,
    pub qty_decimals: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub allow_min_qty: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub allow_max_qty: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub allow_min_amount: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub allow_max_amount: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fee_rate: Option<f64>,
    pub status: Option<i64>,
    pub sort: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
