//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use std::time::SystemTime;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "varieties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub symbol: String,
    pub name: String,
    pub show_decimals: Option<i64>,
    pub min_decimals: Option<i64>,
    pub is_base: Option<bool>,
    pub sort: Option<i64>,
    pub status: Option<i64>,
    pub created_at: Option<SystemTime>,
    pub updated_at: Option<SystemTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
